// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:arcticons:bodyMeasures': typeof import('~icons/arcticons/body-measures')['default']
    'Icon:bx:category': typeof import('~icons/bx/category')['default']
    'Icon:fluentMdl2:productVariant': typeof import('~icons/fluent-mdl2/product-variant')['default']
    'Icon:ic:twotoneAttachMoney': typeof import('~icons/ic/twotone-attach-money')['default']
    'Icon:ic:twotoneCategory': typeof import('~icons/ic/twotone-category')['default']
    'Icon:ic:twotoneInventory2': typeof import('~icons/ic/twotone-inventory2')['default']
    'Icon:mdi:badgeAccountHorizontalOutline': typeof import('~icons/mdi/badge-account-horizontal-outline')['default']
    'Icon:mdi:home': typeof import('~icons/mdi/home')['default']
    'Icon:mdi:loginVariant': typeof import('~icons/mdi/login-variant')['default']
    'Icon:mdi:logout': typeof import('~icons/mdi/logout')['default']
    'Icon:mdi:magnify': typeof import('~icons/mdi/magnify')['default']
    'Icon:mdi:plus': typeof import('~icons/mdi/plus')['default']
    'Icon:mdi:tag': typeof import('~icons/mdi/tag')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:accountCircleOutline': typeof import('~icons/mdi/account-circle-outline')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:shoppingCart': typeof import('~icons/uil/shopping-cart')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
