version: "3"

services:
  web:
    build: 
      context: .
      args:
        VITE_APP_ROOT_API: ${VITE_APP_ROOT_API}
    ports:
      - "9000:9000"
    environment:
      - VITE_APP_ROOT_API=${VITE_APP_ROOT_API}
