version: '3.8'
services:
  app:
    build:  .
    command: sh -c "sleep 20s"
    depends_on:
      - db
    ports:
      - "5000:8000"
    volumes:
      - .:/usr/src/app
  db:
    build: ./mysql/
    restart: always
    ports:
      - '3333:3306' 
    environment:
      - MYSQL_ROOT_PASSWORD=1234