version: "3.9"

services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    container_name: api_nest
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14.6
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: inventory_db
    volumes:
      - postgres_db:/var/lib/postgresql/data


volumes:
  postgres_db:
