package auth

import (
	"fmt"
	"github.com/go-faker/faker/v4"
	"testing"
)

type AccountTest struct {
	Username string `json:"username" faker:"username"`
	Email    string `json:"email" faker:"email"`
	Password string `json:"password" faker:"password"`
}

func TestAccount(t *testing.T) {
	a := AccountTest{}
	err := faker.FakeData(&a)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("%+v", a)
}

// Output:
// {Username:Some random name Email:some@random.mail Password:a1b2c3d4e5f6g7h8i9j0}

// Note: The code above is generated by faker. You can use it to generate fake data for your tests.
// Path: backend\api\auth\auth_test.go

// To run the test, go to backend dir from the project root dir, and you can use the command below:
// go test -v ./...
