version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hiring_team_logistica
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - .:/team-logistics
    command: sh -c "sleep 10 && php artisan migrate --seed"
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=hiring_team_logistica
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    ports:
      - "8080:80"
    depends_on:
      - db
